# 给这个自动化流程起个名字
name: Python CI Pipeline

# 触发条件：当代码推送到 main 分支，或者提交 Pull Request 时自动运行
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 定义具体要执行的任务
jobs:
  build-and-test:
    runs-on: ubuntu-latest  # 在最新的 Ubuntu 系统上运行

permissions: 
   contents: read
   packages: write
   
steps:
         - name: Checkout code
          uses: actions/checkout@v4

         - name: Login to GitHub Container Registery
         uses: docker/login-action@v3
         with:
         registry: ghcr.io
        usersname: ＄{{gothub.actor}}
        password: ＄{{secrets.GITHUB_TOKEN}}

         - name: Build and Push Docker Image
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags:
             ghcr.io/${{github.repository_owner}}/hello world:latest
             ghcr.io/${{github.repository_owner}}/hello world:${{ github.sha }}
   
